name 'dragons'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dragons'
long_description 'Installs/Configures dragons'
version '0.1.0'
