name 'dragons3'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dragons3'
long_description 'Installs/Configures dragons3'
version '0.1.0'
