name 'iron-born'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures iron-born'
long_description 'Installs/Configures iron-born'
version '0.1.0'
