name 'dragons5'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dragons5'
long_description 'Installs/Configures dragons5'
version '0.1.0'
