name 'dragons2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dragons2'
long_description 'Installs/Configures dragons2'
version '0.1.0'
